save_metric_data_multicam_fix_rate:
  ros__parameters:
    rosbag_path: /ros2_bags/provo_river_p1_11_3_25
    lidar_topic: /lio_sam/deskew/cloud_deskewed
    save_folder: /ros2_bags/metric_data_0.5s/synced/provo_river_p1_11_3_25
    save_period: 1.0 # [sec] between saves (real callback rate = save_period * rosbag_playback_rate)
    num_cameras: 3
    camera1_topic: /oak_d_lr_forward/rgb/image_raw
    camera2_topic: /oak_d_lr_left/rgb/image_raw
    camera3_topic: /oak_d_lr_right/rgb/image_raw

    # extrinsic_transforms
    publish_extrinsics: true
    lidar_to_camera1:
      translation: [ -0.04, -0.12, -0.14 ] # x, y, z in meters
      rotation_quaternion: [-0.49628265, -0.50096366,  0.50543674, -0.49726517] # qx, qy, qz, qw (L to Cam)
      parent_frame:  oak_d_lr_forward_rgb_camera_frame
      child_frame: os_lidar
    lidar_to_camera2:
      translation: [ -0.03, -0.18, -0.17] # x, y, z in meters
      rotation_quaternion: [ 0.00931211, -0.70271394,  0.71135208,  0.00919903] # qx, qy, qz, qw (L to Cam)
      parent_frame:  oak_d_lr_left_rgb_camera_frame
      child_frame: os_lidar
    lidar_to_camera3:
      translation: [ -0.1, -0.09, -0.17 ] # x, y, z in meters
      rotation_quaternion: [ 0.69838366,  0.00691528, -0.01040605,  0.71561453] # qx, qy, qz, qw (L to Cam)
      parent_frame:  oak_d_lr_right_rgb_camera_frame
      child_frame: os_lidar