## Processing parameters
data_folder: /data/south_campus
debug: false
continue_processing: false
save_step_size: 500
yolo_model_path: /south_campus_3cls.pt
unaligned_threshold: 0.2 # seconds

## Camera intrinsics
cam_K:  [457.978759765625, 0.0, 387.35205078125, 
        0.0, 457.719482421875, 240.11021423339844, 
        0.0, 0.0, 1.0] # 768 x 480

## MS Map parameters
match_threshold: 0.9
use_dbscan: true
dbscan_eps: 2.0
dbscan_min_samples: 5
cam2point_dist_threshold: 20.0 # [m]