## Processing parameters
data_folder: /docker_ros2_ws/src/oasis2/data/hope_campground_11_3_2025
num_cams: 3
debug: true
continue_processing: false
save_step_size: 10
unaligned_threshold: 0.5 # seconds

## Camera intrinsics
cam_K:  [457.978759765625, 0.0, 387.35205078125, 
        0.0, 457.719482421875, 240.11021423339844, 
        0.0, 0.0, 1.0] # 768 x 480

## YOLO Model
use_yoloe: false
yolo_model_path: /yolo_goose_ground.pt
yolo_conf_threshold: 0.1

## MS Map parameters
match_threshold: 0.9
use_dbscan: true
dbscan_eps: 2.0
dbscan_min_samples: 5
cam2point_dist_threshold: 20.0 # [m]
cam_axis: ['-x', '-y', '+y']  # ['+x', '-x', '+y', '-y']