save_metric_data_multicam:
  ros__parameters:
    rosbag_path: /ros2_bags/rock_canyon_campground_11_3_25
    lidar_topic: /lio_sam/deskew/cloud_deskewed
    save_folder: /ros2_bags/metric_data_dense/rock_canyon_campground_11_3_25
    num_cameras: 3
    camera1_topic: /oak_d_lr_forward/rgb/image_raw
    camera2_topic: /oak_d_lr_left/rgb/image_raw
    camera3_topic: /oak_d_lr_right/rgb/image_raw

    # extrinsic_transforms
    publish_extrinsics: true
    lidar_to_camera1:
      translation: [ -0.12586, 0.021, -0.08154 ] # x, y, z in meters
      rotation_quaternion: [ -0.5, -0.5, 0.5, -0.5 ] # qx, qy, qz, qw (L to Cam)
      parent_frame:  oak_d_lr_forward_rgb_camera_frame
      child_frame: os_lidar
    lidar_to_camera2:
      translation: [ -0.021, -0.12522, -0.08232 ] # x, y, z in meters
      rotation_quaternion: [ 0.0, -0.7071068, 0.7071068, 0.0 ] # qx, qy, qz, qw (L to Cam)
      parent_frame:  oak_d_lr_left_rgb_camera_frame
      child_frame: os_lidar
    lidar_to_camera3:
      translation: [ 0.021, 0.125, -0.08232 ] # x, y, z in meters
      rotation_quaternion: [ 0.7071068, 0.0, 0.0, 0.7071068 ] # qx, qy, qz, qw (L to Cam)
      parent_frame:  oak_d_lr_right_rgb_camera_frame
      child_frame: os_lidar