data_folder: /ros2_bags/holoocean_sim/sparsefull_data
output_folder: /ros2_bags/holoocean_sim/sparsefull_data/output/1_cam_fix
save_average_embeddings: true
debug: true
cam2point_dist_threshold: 20.0 # [m] same as in msmap.yaml

## Terrain params
terrain_classes: ["sidewalk", "grass", "asphalt"] # must match yolo class names & ordering
terrain_threshold: 0.95

## GVD params
og_resolution: 1.0 # Grid cell size in meters [m/cell] (should match LIO-SAM discretization (mappingSurfLeafSize))
max_iterations: 10 # max_itr for GVD floodfill technique
max_deviation: 3.75 # 0.75 [m] / 0.2 [m/voxel] = [voxels]
max_distance: 10.0 # 2.0 [m] / 0.2 [m/voxel] = [voxels]

## Terra params
z_offset_viz: 50.0 # [m]
z_offset_lidar: 1.0 # [m] dist from LiDAR to ground (negative-z means below LiDAR)
cossim_weight_ratio: 100.0
dbscan_params:
  eps: 1.0
  min_samples: 4
search_radius: 0.75
alpha: 0.23
## Region params
region_method: "agglomerative" # options: ["agglomerative", "spectral"]
## Hierarchical Agglomerative params: either List (for where to divide levels at) or Int (for number of levels) respectively
agg_params: [50, 100, 200, 400] # List (for where to divide levels at)
## Hierarchical Spectral params
spec_min_graph_area: 10000 # [m^2]
spec_max_semantic_diff: 0.45 # cos_sim difference