save_metric_data:
  ros__parameters:
    rosbag_path: /ros2_bags/south_campus
    lidar_topic: /lio_sam/deskew/cloud_deskewed
    camera_topic: /oak/rgb/image_raw
    save_folder: /docker_ros2_ws/src/oasis2/data/south_campus_4_21_25

    # extrinsic_transforms
    publish_extrinsics: true
    lidar_to_camera:
      translation: [ -0.15976, 0.0231164, 0.0319886 ] # x, y, z in meters
      rotation_quaternion: [ -0.0075367, -0.6856851, 0.727801, -0.0092125 ] # qx, qy, qz, qw (L to Cam)
      parent_frame:  oak_rgb_camera_frame
      child_frame: os_lidar
