# #Utah Lake Park P1
# # terra: /Data/Terra_Field_Tests/synced/utah_lake_park_p1_11_6_25/output/1_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# terra: /Data/Terra_Field_Tests/synced/sem_avg_fixed/utah_lake_park_p1_11_6_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# nodes_with_GPS:
#   - node_id: 724
#     GPS: [40.23851356398447, -111.73685397600929]
#   - node_id: 1799
#     GPS: [40.241013478923804, -111.74578077810149]

# # Utah Lake Park P2
# # terra: /Data/Terra_Field_Tests/synced/utah_lake_park_p2_11_6_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# terra: /Data/Terra_Field_Tests/synced/sem_avg_fixed/utah_lake_park_p2_11_6_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# nodes_with_GPS:
#   - node_id: 6
#     GPS: [40.23848945684554, -111.73985823885383]
#   - node_id: 23
#     GPS: [40.24086723540858, -111.74647210484386]


# # Rock Canyon Campground
# # terra: /Data/Terra_Field_Tests/synced/rock_canyon_campground_11_3_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# terra: /Data/Terra_Field_Tests/synced/sem_avg_fixed/rock_canyon_campground_11_3_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# nodes_with_GPS:
#   - node_id: 69
#     GPS: [40.291590608766526, -111.60811309375451]
#   - node_id: 162
#     GPS: [40.289423338101, -111.60639935277345]

# #Provo River Trail
# # terra: /Data/Terra_Field_Tests/synced/provo_river_p1_11_3_25_cleaned/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# terra: /Data/Terra_Field_Tests/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# nodes_with_GPS:
#   - node_id: 476
#     GPS: [40.24209422196873, -111.68563227816115]
#   - node_id: 347
#     GPS: [40.24135846017628, -111.68508896649031]


# #Nunns Park
# # terra: /Data/Terra_Field_Tests/synced/nunns_park_p2_10_15_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# terra: /Data/Terra_Field_Tests/synced/sem_avg_fixed/nunns_park_p2_10_15_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
# nodes_with_GPS:
#   - node_id: 477 
#     GPS: [40.33769953414136, -111.61014559512257]
#   - node_id: 162
#     GPS: [40.334908677649494, -111.61361134669112]