data_folder: /docker_ros2_ws/src/oasis2/data/provo_river_p1_11_3_2025
output_folder: /docker_ros2_ws/src/oasis2/data/provo_river_p1_11_3_2025/output/goose_ground_8cls/3_cam
save_average_embeddings: false
debug: true
cam2point_dist_threshold: 20.0 # [m] same as in msmap.yaml

## Terrain params
terrain_classes: ["snow", "leaves", "road", "sidewalk", "gravel", "dirt", "grass", "water"] # must match yolo class names & ordering
terrain_threshold: 0.95

## GVD params
og_resolution: 1.0 # Grid cell size in meters (matches LIO-SAM discretization)
max_iterations: 10 # max_itr for GVD floodfill technique
max_deviation: 3.75 # 0.75 [m] / 0.2 [m/voxel] = [voxels]
max_distance: 10.0 # 2.0 [m] / 0.2 [m/voxel] = [voxels]

## Terra params
z_offset_viz: 50.0 # [m]
z_offset_lidar: -2.5 # [m] dist from LiDAR to ground (negative means below LiDAR)
cossim_weight_ratio: 100.0
dbscan_params:
  eps: 1.0
  min_samples: 4
search_radius: 2.5
alpha: 0.23
## Region params
region_method: "agglomerative" # options: ["agglomerative", "spectral"]
## Agglomerative params
agg_hierarchical_distances: [50, 100, 200, 400] # [m]
## Hierarchical Spectral params
spec_min_graph_area: 10000 # [m^2]
spec_max_semantic_diff: 0.45 # cos_sim difference