---
data_folder: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned
output_folder: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam
num_cams: 3
IMG_W: 768
IMG_H: 480
cam1_K:  [458.17091039, 0.0, 388.71610935, 
        0.0, 457.99950521, 230.87195191, 
        0.0, 0.0, 1.0] # 768 x 480
cam1_dist: [0.03738764, -0.07371669, -0.00024887, 0.00058859] # forward (cam1) - ssp

cam2_K:  [455.47078158, 0.0, 386.00515232, 
        0.0, 455.32530496, 244.20159992, 
        0.0, 0.0, 1.0] # 768 x 480
cam2_dist: [0.04187796, -0.0808205, -0.0001623, -0.00039214] # left (cam2) - ssp

cam3_K:  [456.77801458, 0.0, 378.49188005, 
        0.0, 456.3905806,  240.8612888, 
        0.0, 0.0, 1.0] # 768 x 480
cam3_dist: [0.02182443, -0.04749719, 0.00062508, 0.00044833] # right (cam3) - ssp

terra: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
alpha: 0.26
prediction_method: "3dsg_max" # [ms_avg, ms_max, 3dsg_avg, 3dsg_max]
object_tasks:
  - {task: "parked car", ground_truth: 11} # 2 less cars for 1 cam (i.e. GT=9)
  - {task: "bicycle", ground_truth: 3}
  - {task: "grill", ground_truth: 5} 
  - {task: "building", ground_truth: 6}
  - {task: "pavilion", ground_truth: 5}
  - {task: "garbage", ground_truth: 7}
####   - {task: "bench seat", ground_truth: 11} # not picnic tables (never understood by clip)

#  - task: "get bike from the bicycle rack" # method=3dsg, alpha=0.25 # blue