---
place_nodes_gps: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/nunns_park_p2_10_15_25/output/3_cam/node_gps_dict_nunns_park.pkl
place_nodes_enu: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/nunns_park_p2_10_15_25/output/3_cam/node_enu_dict_nunns_park.pkl

terra: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/nunns_park_p2_10_15_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
alpha: 0.26
topk: 3 # number of top place nodes to select based on the prediction method
prediction_method: "ms_max" # [places, ms_avg, ms_max, 3dsg_avg, 3dsg_max]

#        preferred : set of terrain_ids that should have no penalty (default: None)
#        forbidden : set of terrain_ids that should not be used (default: None)
#        penalties : dict mapping terrain_id -> penalty cost (default: None)'
terrain_preferences:
  preferred:
    # - 0
  forbidden:
    # - 2
  penalties:
    # 0: 1.0
    # 1: 5.0

# [1_short, 1_long, object_context]
unique_object_approach: "1_short"
gamma_obj: 0.7
# start_nodes: [331,531,237]
start_nodes: [[40.336725, -111.612252], # init parking lot (331)
              [40.337650, -111.609428], # end parking lot (531)
              [40.335959, -111.612645]] # base of main bldg stairs (237)
tasks:
  ## Option 1.1: 1 prompt-short
  - {
    query_destination: "underpass" # in underpass
    }
  - {
    query_destination: "honey bucket" # n/a
    }
  - {
    query_destination: "trailer" # truck trailer 
    }
  - {
    query_destination: "dumpster" # by brick building 
    }
  - {
    query_destination: "playground" # in sand 
    }
  
  # ## Option 1.2: 1 prompt-long
  # - {
  #   query_destination: "go in the underpass"
  #   }
  # - {
  #   query_destination: "go to a honey bucket"
  #   }
  # - {
  #   query_destination: "go to the trailer behind the truck"
  #   }
  # - {
  #   query_destination: "go to the dumpster by the brick building"
  #   }
  # - {
  #   query_destination: "go to the playground in sand"
  #   }

  # ## Option 2: Separate object from context
  # - {
  #   object: "underpass",
  #   # context: "in the underpass"
  #   context: "go in" # no obj
  # }
  # - {
  #   object: "honey bucket",
  #   # context: "blue honey bucket"
  #   context: "blue" # no obj
  # }
  # - {
  #   object: "trailer",
  #   # context: "trailer behind the truck"
  #   context: "behind the truck" # no obj
  # }
  # - {
  #   object: "dumpster",
  #   # context: "dumpster by the brick building"
  #   context: "by the brick building" # no obj
  # }
  # - {
  #   object: "playground",
  #   # context: "playground in sand"
  #   context: "in sand" # no obj
  # }
  