---
place_nodes_gps: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam/node_gps_dict_provo_river.pkl
place_nodes_enu: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam/node_enu_dict_provo_river.pkl

terra: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
alpha: 0.26
topk: 3 # number of top place nodes to select based on the prediction method
prediction_method: "ms_max" # [places, ms_avg, ms_max, 3dsg_avg, 3dsg_max]

#        preferred : set of terrain_ids that should have no penalty (default: None)
#        forbidden : set of terrain_ids that should not be used (default: None)
#        penalties : dict mapping terrain_id -> penalty cost (default: None)'
terrain_preferences:
  preferred:
    # - 0
  forbidden:
    # - 2
  penalties:
    # 0: 1.0
    # 1: 5.0

# [1-short, 1-long, object+context, ensemble]
unique_object_approach: "object+context"
gamma_obj: 0.7
tasks:
  # ## Option 1.1: 1 prompt-short
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "bridge" # brown, over river
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "bridge" # white, curved
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "playground" 
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "garbage" # parking lot 
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "garbage" # red bldg, bathrooms 
  #   }
  
  # ## Option 1.2: 1 prompt-long
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the large brown bridge over the river"
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the small white bridge in the woods"
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the playground"
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the garbage in the parking lot"
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the garbage by the red building"
  #   }

  ## Option 2: Separate object from context
  - {start_node: 162, # Place node ID for the starting point
    object: "bridge",
    # context: "large brown bridge over the river"
    context: "large brown over the river" # no obj
  }
  - {start_node: 162, # Place node ID for the starting point
    object: "bridge",
    # context: "small white bridge in the woods"
    context: "small white in the woods" # no obj
  }
  - {start_node: 162, # Place node ID for the starting point
    object: "playground",
    # context: "playground in sand"
    context: "in sand" # no obj
  }
  - {start_node: 162, # Place node ID for the starting point
    object: "garbage",
    # context: "garbage in the parking lot"
    context: "in the parking lot" # no obj
  }
  - {start_node: 162, # Place node ID for the starting point
    object: "garbage",
    # context: "garbage by the red building"
    context: "by the red building" # no obj
  }
  