---
place_nodes_gps: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam/place_nodes_gps.pkl

terra: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/provo_river_p1_11_3_25_cleaned/output/3_cam/Terra_20.0mimgembs_nodist1img_beta1gamma100autoagglomerativecluster.pkl
alpha: 0.26
topk: 1 # number of top place nodes to select based on the prediction method
prediction_method: "ms_avg" # [places, ms_avg, ms_max, 3dsg_avg, 3dsg_max]

#        preferred : set of terrain_ids that should have no penalty (default: None)
#        forbidden : set of terrain_ids that should not be used (default: None)
#        penalties : dict mapping terrain_id -> penalty cost (default: None)'
terrain_preferences:
  preferred:
    # - 0
  forbidden:
    # - 2
  penalties:
    # 0: 1.0
    # 1: 5.0

tasks:
  - {start_gps: [40.248, -111.658], # GPS coordinates for the starting point [LATITUDE, LONGITUDE] 
    query_destination: “Go to the large brown bridge over the river”
    }
  
