---
place_nodes_gps: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/utah_lake_park_p1_11_6_25/output/3_cam/node_gps_dict_marina_p1.pkl
place_nodes_enu: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/utah_lake_park_p1_11_6_25/output/3_cam/node_enu_dict_marina_p1.pkl

terra: /ros2_bags/metric_data_0.5s/synced/sem_avg_fixed/utah_lake_park_p1_11_6_25/output/3_cam/Terra_20.0mimgembs_nodist1img_agglomerativecluster.pkl
alpha: 0.26
topk: 3 # number of top place nodes to select based on the prediction method
prediction_method: "ms_max" # [places, ms_avg, ms_max, 3dsg_avg, 3dsg_max]

#        preferred : set of terrain_ids that should have no penalty (default: None)
#        forbidden : set of terrain_ids that should not be used (default: None)
#        penalties : dict mapping terrain_id -> penalty cost (default: None)'
terrain_preferences:
  preferred:
    # - 0
  forbidden:
    # - 2
  penalties:
    # 0: 1.0
    # 1: 5.0

unique_object_approach: "object+context" # [1-short, 1-long, object+context, ensemble]
gamma_obj: 0.7
tasks:
  # ## Option 1.1: 1 prompt-short
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "dumpster" # at end of the road
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "stop sign" y
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "fire hydrant" 
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "dumpster" # by white fence
  #   }
  
  # ## Option 1.2: 1 prompt-long
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the dumpster at end of road by rocks and water"
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the stop sign"
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the fire hydrant"
  #   }
  # - {start_node: 162, # Place node ID for the starting point
  #   query_destination: "go to the dumpster in white fence by tree"
  #   }

  ## Option 2: Separate object from context
  - {start_node: 162, # Place node ID for the starting point
    object: "dumpster",
    # context: "dumpster near the end of a road by rocks and water"
    context: "near the end of a road by rocks and water"
  }
  - {start_node: 162, # Place node ID for the starting point
    object: "stop sign",
    # context: "stop sign by road"
    context: "by road"
  }
  - {start_node: 162, # Place node ID for the starting point
    object: "fire hydrant",
    # context: "fire hydrant on grass in RV park"
    context: "on grass in RV park"
  }
  - {start_node: 162, # Place node ID for the starting point
    object: "dumpster",
    # context: "dumpster in white fence by tree"
    context: "in white fence by tree"
  }
  
  # ## Option 3: Ensemble of prompts
  # - start_node: 162 # Place node ID for the starting point
  #   prompts: 
  #     - "dumpster" # object
  #     - "garbage" # object synonym
  #     - "go to the dumpster" # go to + object
  #     - "dumpster near the end of a road by rocks and water" # object + context
  #     - "go to the dumpster at end of road by rocks and water" # full task description
  
  # - start_node: 162 # Place node ID for the starting point
  #   prompts: 
  #     - "stop sign" # object
  #     - "red road sign" # object synonym
  #     - "go to the stop sign" # go to + object
  #     - "stop sign by road" # object + context
  #     - "go to the stop sign by road" # full task description
  
  # - start_node: 162 # Place node ID for the starting point
  #   prompts: 
  #     - "fire hydrant" # object
  #     - "fireplug" # object synonym
  #     - "go to the fire hydrant" # go to + object
  #     - "fire hydrant on grass in RV park" # object + context
  #     - "go to the fire hydrant on grass in RV park" # full task description

  # - start_node: 162 # Place node ID for the starting point
  #   prompts: 
  #     - "dumpster" # object
  #     - "garbage" # object synonym
  #     - "go to the dumpster" # go to + object
  #     - "dumpster in the white fence by tree" # object + context
  #     - "go to the dumpster in white fence by tree" # full task description