---
data_folder: /ros2_bags/holoocean_sim/dense18_test
output_folder: /ros2_bags/holoocean_sim/dense18_test/output/1_cam
gt_bboxes_csv: /docker_ros2_ws/src/terra/terra_eval/config/sim/dense18_gt_bboxes.csv
gt_obj_names: /docker_ros2_ws/src/terra/terra_eval/config/sim/gt_object_names.yaml
case: "dense"
# bounds: [5, 70, -70, -20, 0, 100] # [xmin, xmax, ymin, ymax, zmin, zmax] # HOLOFrame
bounds: [0, 65, -43, 7, -8.49, 91.51] # [xmin, xmax, ymin, ymax, zmin, zmax] # LIOSAMFrame

terra: /ros2_bags/holoocean_sim/dense18_test/output/1_cam/Terra_20.0mimgembs_nodist1img_beta1gamma100.0agglomerativecluster.pkl
alpha: 0.26
prediction_method: "ms_avg" # [ms_avg, ms_max, ms_medoid, ms_trim, 3dsg_avg, 3dsg_max]
trim: 0.6 # only used in ms_trim method
object_tasks:
  - {task: "find a car", label: 7}
  - {task: "find a bike rack", label: 3}
  - {task: "find a semi truck", label: 22}
  - {task: "find a street lamps", label: 26}
  - {task: "find a bench", label: 2}