---
terra: /path/to/Terra.pkl
alpha: 0.23
prediction_method: "ms_avg" # [ms_avg, ms_max, 3dsg]

#        preferred : set of terrain_ids that should have no penalty (default: None)
#        forbidden : set of terrain_ids that should not be used (default: None)
#        penalties : dict mapping terrain_id -> penalty cost (default: None)'
terrain_preferences:
  preferred:
    - 0
  forbidden:
    - 2
  penalties:
    0: 1.0
    1: 5.0

queries:
  start: "description of start location" # OR leave blank/null to not use start query
  destination: "description of destination location"